services:
  postgres:
    image: tyamadabiodataeng/pharma-dbms-postgres
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: ../dockerfiles/postgres/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - pharmadb_pg_data:/var/lib/postgresql/data
    networks:
      - pharmadb-network
  django:
    image: tyamadabiodataeng/pharma-dbms-django
    container_name: django
    build:
      context: ./app
      dockerfile: ../dockerfiles/django/Dockerfile
      args:
        DIR_WORK: "/usr/src"
        ENV_YAML: "environment.yaml"
        VENV: "dbms-django"
    command: mamba run --name dbms-django gunicorn config.wsgi.prod:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src
    expose:
      - "8000"
    env_file:
      - ./app/config/.env
    depends_on:
      - postgres
    networks:
      - pharmadb-network
  nginx:
    image: tyamadabiodataeng/pharma-dbms-nginx
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: ../dockerfiles/nginx/Dockerfile
    volumes:
      - ./app/static:/usr/src/static
      - ./app/media:/usr/src/media
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - pharmadb-network
  jupyter:
    build: 
      context: ./notebooks
      dockerfile: ../dockerfiles/jupyter/Dockerfile
      args:
        DIR_WORK: "/usr/src"
        ENV_YAML: "environment.yaml"
        VENV: "dbms-jupyter"
    image: tyamadabiodataeng/pharma-dbms-jupyter
    container_name: jupyter
    command: mamba run --name dbms-jupyter jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./notebooks:/usr/src
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    networks:
      - pharmadb-network

networks:
  pharmadb-network:
    driver: bridge

volumes:
  pharmadb_pg_data:
