name: dbms-django-dev
channels:
  - conda-forge
dependencies:
  - python=3.13
  - django
  - django-ninja
  - structlog
  - psycopg
  - uvicorn
  - gunicorn
  - django-auditlog
  - django-environ
  - django-extensions
  - django-filter
  - django-guardian
  - django-import-export
  - django-silk
  - django-structlog
  - rdkit
  - black
  - ruff
  - mypy
  - tox
  - django-debug-toolbar
  - pytest
  - pytest-django
  - pytest-randomly
  - pytest-cov
  - factory_boy
  - mkdocs
